spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://127.0.0.1:3306/security-demo?useSSL=false

  session:
    store-type: none


#security:
#  basic:
#    enabled: false

#应用级配置
earthchen:
  security:
#    browser:
##      配置自定义登录页,不配置则为默认登录页
#      loginPage: /demo-signIn.html

    validateCode:
      imageCode:
#         设置图形验证码的长度为6，不配置则为默认验证码属性
        length: 4
        width: 67
#        url: /user,/user/*
    social:
      qq:
        app-id: 100550231
        app-secret:
        # 设置providerId
        providerId: callback.do
        # 将社交登录social前缀的/auth改为以下内容

      filterProcessesUrl: /social-auth
        # 最终url为/social-auth/callback.do



